networks:
  mls_network:
    external: true

services:
  server:
    build: ./
    restart: always
    image: mls_server
    ports: 
      - "8080:8080"
    networks:
      mls_network:
        ipv4_address: 172.31.0.2
  broker:
    image: eclipse-mosquitto:2.0.20
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes: 
      - ./broker/config:/mosquitto/config
      - ./broker/log:/mosquitto/log
    depends_on:
      - server
    networks:
      mls_network:
        ipv4_address: 172.31.0.4
